### ISSUE TITLE
How to Use this Library

### ISSUE THREAD

**Issue by ajdali** [EncodiaDotCo/OutlineView#1]
Hi There,
I am trying to implement a file system watcher display on macOS. I would like to have a session with you sometime on how to use this library.

**Comment by EncodiaDotCo** [comment]
Okay, cool. Have you tried it out yet? Any specific questions? There is some example code on the front page, but maybe I should add some more explanation.

**Comment by ajdali** [comment]
Hey @EncodiaDotCo I'm not sure as a client which view to use, it seems that you have just tested outline view and I wanted to see basically how to use it in general vs in your specific example

**Comment by EncodiaDotCo** [comment]
There is only one view in this package, `OutlineView`. The basic idea is borrowed from other UI libraries with lazy expandable tree/outlines. You give it a model, as in the example, which is a tree of objects implementing `TreeNodeProtocol`.  That protocol give the `OutlineView` the info it needs to lazily build the tree as needed.

**Comment by ajdali** [comment]
Do you think this library can work if i have a file system of thousands (maybe 10s of thousands) of files and performance would be good if i expanded collapsed at various nesting levels in the tree?

**Comment by EncodiaDotCo** [comment]
I think it should work. I should tweak the code (1 line change) to use SwiftUI's `LazyVStack` instead of `VStack`, because that could be an issue you expand 100's or 1000's of nodes at the same time.

**Comment by ajdali** [comment]
yeah, keep me updated on updates and releases. currently trying to test it out and get a feel for the methods. i was thinking of creating like a shadow view of a large array with all the files and using your view to just lazy load whatever item is expanded

**Comment by ajdali** [comment]
@EncodiaDotCo I noticed that when I try to modify this tree (like changing the name of the root) since the TreeNodeProtocol requires class based implementation the viewmodel does not register the changes. I have to create a new class and modify the data which causes the whole drop down view to collapse and rerender. Can you describe a use case for efficiently modifying/adding/deleting elements of this tree without overhead of creating new class instances and how i would achieve this with the library?

**Comment by EncodiaDotCo** [comment]
You can definitely do this. The `TreeNodeProtocol` inherits from `ObservableObject`. So in the example code, if you were going to change the `name` of a node, you'd change name into: `@Published var name: String`. Then changes to it will get picked up. In my code, this does not cause the `OutlineView` to collapse and re-render. Follow a similar pattern for adding or removing children. You might have to make a property `@Published` or manually fire `objectWillChange` from the tree node, but the `OutlineView` will re-render with different children while keeping it's expanded/collapsed state.

**Comment by ajdali** [comment]
I'm trying to pull the nodes out into a view model so that i can manage the state of the tree in a VM. And I can add methods to stream add events to the tree, deletion, etc. But I keep getting 
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/110415187/195723855-9b9ae1f0-2d8e-4893-8d91-cf6665e6322e.png">

By changing instead of @State to @ObservedObject
<img width="922" alt="image" src="https://user-images.githubusercontent.com/110415187/195723948-84780e25-e9a3-492c-ac66-0c635d556167.png">

Is this the right design pattern for your library? What am I doing wrong?

**Comment by ajdali** [comment]
I added @MainActor to the entire view model class, it would be helpful if you had an example of VM in your code too. thanks for the help so far

**Comment by EncodiaDotCo** [comment]
I was just writing to recommend that (marking the view model class). I think the actor stuff is not 100% working in some corner cases of SwiftUI. Maybe the new Fall 2022 release fixes the issues I saw last year.

**Comment by ajdali** [comment]
I was able to implement a method to add a Node to the tree. However when I tried adding 10,000 nodes in one method (representing 10,000 files or leaf nodes) I got 100% CPU usage and the whole process froze my app for about 2 seconds before loading the entire view. 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/110415187/195904006-1560f8ab-e934-4c62-a427-ec254c27738f.png">
I basically implement the insert like inserting into a trie structure using a file path delimited by the "/" each directory is a node in the tree. Would you recommend any other approach to using this library? I'm thinking since the individual nodes are observable objects as well there is always messages getting sent to the view that data is changing. curious how i can prevent this.

**Comment by EncodiaDotCo** [comment]
You added 10,000 children to one node, or 10,000 nodes total in the whole tree?  Either way, I'm guessing the `VStack` can't handle it. Let me try updating the code to use SwiftUI's `LazyVStack`, which might be able to handle the 10,000 nodes. I'll try to update the code today and post back here in a few hours.

**Comment by ajdali** [comment]
I added the 10,000 nodes total in the whole tree in one go, at various nesting levels under one root node. think of like adding all the files in my file system and representing it with your structure. and sounds good

**Comment by ajdali** [comment]
I didnt see any issues with expand collapsing, it was when the data was getting populated into the Tree there was some lag. maybe there is some way to control when the view actually should change, rather than with every update to the published properties

**Comment by EncodiaDotCo** [comment]
I should update it to use LazyVStack anyway, but that sounds like it could be something not related to this package. Because if your root tree is only displaying, say 10-100 files, then the outline shouldn't have to know about the other 10,000. The TreeNodeProtocol is lazy for that reason. If you can attach sample code here, I can take a look at it.

**Comment by ajdali** [comment]
Sure let me share you my code. Built mostly from your example code
```

import Foundation
import EncodiaOutlineView
import SwiftUI

@MainActor class BackupTreeViewModel: ObservableObject {
    @Published var backupTree: [BackupNode] = [BackupNode]()
    
    init() {
        makeOutlineRoots()
    }
    
    func makeOutlineRoots() {
        backupTree.append(BackupNode(path: "SEA-15471")) //this would be grpc to get the current host name
        //server side steam until it closes from grpc
    }
    
    func addBackupItem(newPath: String, newStatus: Status, isFileAdded: Bool) -> Bool {
        var eachDirectory = newPath.components(separatedBy: "/")
        eachDirectory[0] = "/"
        var currIndex = 0
        var currBackupItem = backupTree[0] //the current machine to start at
        while(currIndex < eachDirectory.count) {
            if(currIndex == eachDirectory.count - 1) { //is a folder and last file
                var truncatedPath = eachDirectory[0...currIndex].joined(separator: "/")
                if(truncatedPath != "/") {
                    truncatedPath.removeFirst()
                }
                
                if(isFileAdded) {
                    currBackupItem._children!.append(BackupNode(path: truncatedPath, isFile: true, status: newStatus/*, parent: currBackupItem*/))
                } else {
                    currBackupItem._children!.append(BackupNode(path: truncatedPath, status: newStatus/*, parent: currBackupItem*/))
                }
            } else {
                
                if(currBackupItem._children == nil) {
                    return false
                }
                
                var foundIndex = -1
                //look for the child if found dig into that
   checkExists: for childIndex in 0..<currBackupItem._children!.count {
                    if(currBackupItem._children![childIndex].name == eachDirectory[currIndex]) {
                        foundIndex = currIndex
                        currBackupItem = currBackupItem._children![childIndex]
                        break checkExists
                    }
                }
                
                //child not already found create and repeat process
                if(foundIndex == -1) {
                    var truncatedPath: String = eachDirectory[0...currIndex].joined(separator: "/")
                    if(truncatedPath != "/") {
                        truncatedPath.removeFirst()
                    }
                    
                    currBackupItem._children!.append(BackupNode(path: truncatedPath, status: newStatus/*, parent: currBackupItem)*/))
                    let sizeForEnd = currBackupItem._children!.count
                    currBackupItem = currBackupItem._children![sizeForEnd - 1]
                }
            } //end else
            
            currIndex += 1
        }
        return true
    }//end add method
    
    func addAll() {
        for newPath in FILE_LIST_TEST {
            addBackupItem(newPath: newPath, newStatus: .processing, isFileAdded: true)
        }
    }
}

enum Status {
    case paused
    case processing
    case completed
    case error
}


final class BackupNode: TreeNodeProtocol {
    let id: UUID
    @Published var path: String
    let depth: Int
    @Published var currStatus: Status
    @Published var parent: BackupNode? = nil
    let isFile: Bool
    @Published var _children: [BackupNode]? = nil
    
    var name: String {
        if path == "/" {
            return "/"
        }
        if let index = path.lastIndex(of: "/") {
            let name = String(path.suffix(from: index).dropFirst())
            return name
        } else {
            return "(null)"
        }
    }
    
    var type: String {
        if(isFile) {
            return "File"
        } else {
            return "Folder"
        }
    }
    
    var parentName: String {
        if(parent == nil) {
            return "No Parent"
        } else {
            return parent!.name
        }
    }
    
    init(path: String, isFile: Bool = false, status: Status = .processing, depth: Int = 0, parent: BackupNode? = nil) {
        self.id = UUID()
        self.path = path
        self.depth = depth
        self.currStatus = status
        self.isFile = isFile
        if(!isFile) {
            _children = []
        }
        self.parent = parent
    }
    
    var canHaveChildren: Bool { !isFile }
    var isLoadingChildren: Bool { false }
    
    /// Lazy computed property
    var children: [BackupNode] {
        return _children!
    }
}

struct BackupTreeView: View {
    
    //@State var roots: [BackupNode] = makeOutlineRoots() //take this out into a view model
    @ObservedObject var backupContent = BackupTreeViewModel()
    @StateObject var selection = OutlineViewSingleSelectionModel<BackupNode>()
    // @StateObject var selection = OutlineViewMultiSelectionModel<Thing>()
    @State var expansion: Set<UUID> = []
    
    var body: some View {
        HStack {
            ScrollView {
                OutlineView(roots: backupContent.backupTree, selection: selection, expansion: $expansion) { node in
                    Text("Full Path: \(node.path)...Name: \(node.name)... Parent: \(node.parentName)")
                }//.onChange(of: expansion, perform: {param in print(param)})
            }
            .frame(width: 800)
            Divider()
                .frame(maxWidth: .infinity)
            Button("Add All", action: {backupContent.addAll()})

        }
    }
}
```

**You can run the view, and click the button to add all the elements. If you have any redesign suggestions id be open to it. Our team will be sending me a all the files being backed up and i need to track the status of the files and display them with your view. You can generate a array of unix string files like /Users/Applications/test.txt and make a variable FILE_LIST_TEST to hold them and my code will run**

**Comment by ajdali** [comment]
My guess is I am not using the lazy computed property properly, I'm populating the entire tree in one go. But regardless that is going to be my use case. I might need to use an auxiliary structure to hold the tree and based on expand/collapsing copy the data from that auxiliary structure into your outline view. im no expert on swiftui rendering but need to consider performance as well. each time an observable object is updated, the view is re rendered is my understanding

**Comment by EncodiaDotCo** [comment]
Hi @ajdali. I updated the package to use `LazyVStack`, and I added an example to the Readme that may help you. It shows an example filesystem browser. It uses a background thread to load files. You may not need that, in which case you can skip the `DispatchQueue` and the sets to `isLoadingChildren`. That property exists so the UI can give some indicator when a background thread is loading the child nodes.

**Comment by ajdali** [comment]
thank you very much ill take a look

**Comment by ajdali** [comment]
@EncodiaDotCo I see that you currently have the UI structured that any click on the HStack triggers expand/collapse. In the case where I am adding a check box on the node for a user to click, how to I configure your library to only expand/collapse when the chevron arrow is clicked?

```
private func plainTapGesture() {
        onNodeClick?(node)
        let canExpand = node.canHaveChildren
        // Different ways to do selection/expansion behavior.
        // 1. Any tap on entire HStack causes both a) selection to go to this node, b) toggle expansion. The problem with
        //    this is that you have an open folder. You click on it to maybe see it's stats or just select it, and everything
        //    closes up. I don't like that.
        // 2. Only change the status if the click is on an already selected item
        // print("Node tapped: \(node.id), selection: \(selection?.id)")
        let alreadySelected = selection.contains(node)
        if !selection.allowsSelection || alreadySelected {
            if canExpand {
                toggleExpansion(node.id)
            }
        } else {
            selection.removeAll()
            selection.add(node)
        }
        log.debug("plainTapGesture canExpand=\(canExpand), alreadySelected=\(alreadySelected), node.id=\(String(describing:node.id))")
    }
```

**Comment by EncodiaDotCo** [comment]
There is no configuration for that now, but I could add one in next few days. 

But actually I can't reproduce the bug you describe. If I have a checkbox, then clicking it changes the checkbox and not the expand/collapse state.

If you can show some example code, post it here. Actually, it would better to open a new issue for this topic and post it there.
